### PR TITLE
include DNSSEC RRs for all QTn's

### PR DESCRIPTION
**Pull request by samuelweiler**
If some don't exist, then there will be a negative answer proof (an NSEC or NSEC3 RR).  I'm still wondering if there are weird edge cases here....

### CODE REVIEW

**Comment by raybellis** [comment]
this needs a little work before merging - it needs to be clear that the DNSSEC records that would be returned would be those for the QTYPE and QTn records that actually made it into the response, not all of those that were in the query.

**Comment by samuelweiler** [comment]
One of the edge cases around negative answers: assume a name with a A and AAAA record but no MX record.  QTYPE = A, QTn= MX, AAAA.

An NSEC or NSEC3 record is sent in order to prove that MX does not exist (e.g. MX).  The (misbehaving) server sends QTn = MX, AAAA in the answer.  It includes an NSEC record to prove that the MX does not exist.  It (erroneously or maliciously) does not include the AAAA record - a non-validating resolver sees this as a negative answer - a claim that the AAAA doesn't exist. But the NSEC record proves otherwise.

**Comment by vttale** [comment]
Sam, I'm unclear how your edge case scenario can be a realistic operational problem.  If the authoritative server is giving an inconsistent answer, then it's completely fair for a resolver, validating or not, to have undefined behaviour as far as how it interprets it.

**Comment by vttale** [comment]
I do agree that types that don't exist should be proven by a relevant negative cover, which maybe Ray also intended but wasn't clear from the wording of hist "records that would be returned ..." comment.

**Comment by raybellis** [comment]
It's in the following paragraphs:

> A negative answer from a signed zone MUST contain the appropriate authenticated denial of existence records, per {{!RFC4034}} and {{!RFC5155}}.

It could probably be made more explicit that this also applies to proof of non-existence for QTYPEs and not just the QNAME.

**Comment by raybellis** [comment]
This has been resolved by the rewrite of section 3.2

**Pull request closed without merging**
